f = open("Read.txt")
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
f.close()

f = open("Read.txt")
f.seek(9)
print(f.tell())
print(f.readline())
f.seek(0)
print(f.tell())
print(f.readline())